server:
  port: 8081

spring:
  application:
    name: ai-assistant-service
  ai:
    openai:
      api-key: ${GEMINI_API_KEY:senin-api-key}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        options:
          model: gemini-2.5-flash
          temperature: 0.7
