server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # API isteklerini portfolio-service'e yönlendir
    location /api/ {
        proxy_pass http://portfolio-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # AI isteklerini ai-assistant-service'e yönlendir
    location /ai/ {
        proxy_pass http://ai-assistant-service:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
