server:
  port: 8080

jwt:
  secret: InWallet2026HackathonSecretKeyForJWTMustBe256BitsLong
  expiration: 3600000      # 1 saat (ms) - Güvenlik için JWT süresini kısalttık
  refreshExpiration: 604800000 # 7 gün (ms) - Refresh token uzun süreli kalabilir

spring:
  application:
    name: portfolio-service
  datasource:
    url: jdbc:postgresql://localhost:5433/wallet_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 600000   # 10 dakika (ms cinsinden)

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: portfolio-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
